### ISSUE TITLE
Check credits with Shagu again

### ISSUE THREAD

**Issue by Cephel** [Cephel/dank-addon-pack#10]
@shagu

I switched from shaguUi to pFUI for scaffolding, just wanna reconfirm if you're okay with the credits like they are right now

**Comment by shagu** [comment]
Yes I'm fine with it :)

Just as a suggestion, I don't get the point why you're shipping DPSMate **and** SWStats, aswell as aux-addon **and** auctioneer. I've also seen that your including EquipCompare which is kind of included in pfUI. Also a SellValue alike module is existing there ;)

Cheers, Shagu

**Comment by Cephel** [comment]
Okay, I'll try to explain
SWStats is required for realmplayers data contribution, but I like DPSmate a lot myself.
Aux is great for posting auctions but not for saving them on the go, ie you loot an item and you don't know what it's roughly worth, as aux does no auction house scans and just takes the "is" value.
I have to test the EquipCompare vs the inbuilt pFUI functionality, chances are there's something I don't like about it.
As for the sellvalue, I take it it generates them when you visit a vendor? Informant contains a database of most items so you already have the sell value available without visiting the vendor a couple of times. It also shows how high an item stacks for.

**Comment by shagu** [comment]
pfUI also has it's own database for buy/sell values: https://github.com/shagu/pfUI/blob/master/env/selldata.lua
Which turned out to be more accurate than the one from Informant :)
(e.g Informant shows for http://db.vanillagaming.org/?item=11632 ~70silver)

**Comment by Cephel** [comment]
Interdasting, I'll give it a spin
